#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & 
nitrogen --restore  &
/home/iufb/.config/polybar.old/launch.sh  &
ulauncher &
gwe &
udiskie &
dunst &
picom &
xsetroot -cursor_name left_ptr &

bspc monitor -d  󰇩 󰈖  󰇈  󰇚  
bspc config border_width         1
bspc config window_gap          10
bspc config -d '^2' window_gap 0

bspc config window_transition_slide 1
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	     false

# bspc rule -a Microsoft-edge  desktop='^2' window_gap=0
# bspc rule -a Brave-browser  desktop='^2' window_gap=0
# bspc rule -a Thorium-browser  desktop='^2' window_gap=0
bspc rule -a Microsoft-edge floating=on sticky
bspc rule -a Thunar desktop='^3'
bspc rule -a Nemo desktop='^6'
bspc rule -a Insomnia desktop='^6'

bspc rule -a qBittorrent desktop='^7'
bspc rule -a Spotify desktop='^4'
bspc rule -a obsidian desktop='^5'
