import = ["/home/iufb/.config/alacritty/themes/themes/everfores.yml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "IosevkaNerdFontMono"
style = "Bold"

[font.italic]
family = "IosevkaNerdFontMono"
style = "italic"

[font.normal]
family = "IosevkaNerdFontMono"
style = "Regular"

[window]
opacity = 0.9
startup_mode = "Maximized"
